home/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "home"
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("", views.home, name="home"),
    path("register/", views.register, name="register"),
    path("users/", views.get_users, name="users"),
    path("user_info", views.user_info, name="user_info"),
]

wish_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("", include("wish_list_app.urls", namespace="wish_list_app")),
    path("social-auth/", include("social_django.urls", namespace="social")),
]

wish_list_app/urls.py
from django.urls import path
from . import views

app_name = "wish_list_app"
urlpatterns = [
    path("wish_lists", views.view_all_wish_lists, name="all_wish_lists"),
    path("reserved_gifts/", views.view_reserved_gifts, name="view_reserved_gifts"),
    path("child_register", views.add_child_user, name="child_register"),
    path(
        "child_register_done/<username>",
        views.child_register_done,
        name="child_register_done",
    ),
    path("add_list", views.add_wish_list, name="add_wish_list"),
    path("add_list/<username>", views.add_wish_list, name="add_wish_list_user"),
    
    path("add_gift", views.add_gift, name="add_gift"),
    path("add_gift/<slug:list_name>", views.add_gift, name="add_gift_list"),
    path("reserved/<int:gift_id>", views.reserve_gift, name="reserve_gift"),
    path("find_meta", views.find_meta_info, name="find_meta"),
    path("delete_gift/<int:gift_id>", views.delete_gift, name="delete_gift"),
    path("cancel_gift_reservation/<int:gift_id>", views.cancel_gift_reservation, name="cancel_gift_reservation"),
    path(
        "<username>/<slug:list_name>/<slug:gift_slug>/edit/",
        views.edit_gift,
        name="edit_gift",
    ),
    path("<username>/<slug:list_name>/", views.view_wish_list_gifts, name="gift_lists"),
    path("<username>/", views.view_wish_list, name="user_lists"),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Hasło", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Powtórz hasło", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]

    def clean_password2(self):
        cd = self.cleaned_data
        if cd.get("password") != cd.get("password2"):
            raise forms.ValidationError("Hasła nie są takie same.")
        return cd.get("password2")

    def clean_email(self):
        data = self.cleaned_data.get("email")
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("Ten mail jest już zajęty.")
        return data

home/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from .forms import UserRegistrationForm


def home(request):
    return render(request, "home.html")


def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data.get("password"))
            # Save the User object
            new_user.save()
            return render(
                request, "registration/register_done.html", {"new_user": new_user}
            )
    else:
        user_form = UserRegistrationForm()

    return render(request, "registration/register.html", {"user_form": user_form})


def get_users(request):
    all_users = User.objects.filter(is_superuser=False)
    return render(request, "home/user_list.html", {"all_users": all_users})


def user_info(request):
    return render(request, "home/user_info.html", {"user": request.user})

home/templates/base.html
{% load static %}
<!doctype html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %} {% endblock %}</title>
        <!-- Bootstrap CSS -->
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <!-- custom js and css -->
        <link rel="manifest" href="{% static 'manifest.json' %}">
        <link href='{% static "css/base.css" %}' rel="stylesheet">
        <link href='{% static "css/style.css" %}' rel="stylesheet">
    </head>
    <body>
        {% include "navbar.html" %}
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        {% include "footer.html" %}

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    </body>
</html>

home/templates/footer.html
<footer class="py-3 my-4 border-top">
    <p class="text-center text-muted">© {% now "Y" %} by Filip Adamek</p>
</footer>

home/templates/home.html
{% extends "base.html" %}

{% block title %}Lista prezentów{% endblock %}

{% block content %}
<div class="px-4 pt-5 my-5 text-center">
    {% load static %}
        <img class="d-block mx-auto mb-2 rounded" src="{% static 'images/wish_list_logo.jpg' %}" alt="wish list logo" width="300rem" height="300rem">
    <h1 class="display-4 fw-bold">Witaj w aplikacji lista prezentów</h1>

    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">
            {% if request.user.is_authenticated %}
                Co chcesz zrobić?
            {% else %}
                Aby przejść dalej zaloguj sie lub zarejestruj.
            {% endif %}
        </p>
    </div>


        {% if request.user.is_authenticated %}
        <div class="mx-auto p-2">
            <a type="button" class="btn btn btn-outline-primary btn-lg px-4" href="{% url 'home:users' %}">
                <img src="{% static 'images/people.svg' %}" width="30" height="30" alt="home logo"/>
                Zobacz obdarowanych
            </a>
        </div>
        <div class="mx-auto p-2">
            <a type="button" class="btn btn-outline-success btn-lg px-4" href="{% url 'wish_list_app:all_wish_lists' %}">
                <img src="{% static 'images/view-list.svg' %}" width="30" height="30" alt="home logo"/>
                Zobacz listy prezentów
            </a>
        </div>
        <hr class="mt-2 mb-3"/>
        <div class="mx-auto p-2">
            <a type="button" class="btn btn-primary btn-lg px-4" href="{% url 'wish_list_app:add_wish_list' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-lines-fill" viewBox="0 0 16 16">
                    <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5m.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1z"/>
                </svg>
                Dodaj nową listę prezentów</a>
        </div>
        <div class="mx-auto p-2">
            <a type="button" class="btn btn-success btn-lg px-4" href="{% url 'wish_list_app:add_gift' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                </svg>
                Dodaj nowy prezent
            </a>
        </div>
        {% else %}
            <a type="button" class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'home:login' %}">Zaloguj</a>
            <a type="button" class="btn btn-outline-secondary btn-lg px-4" href="{% url 'home:register' %}">Zarejestruj</a>
        {% endif %}
    </div>
</div>


{% endblock %}

home/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand mb-0 h1" href="{% url 'home:home' %}">
      {% load static %}
      <img src="{% static 'images/gift.svg' %}" width="30" height="30" alt="home logo"/>
      Start
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:users' %}">
            <img src="{% static 'images/people.svg' %}" width="30" height="30" alt="home logo"/>
            Użytkownicy
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'wish_list_app:all_wish_lists' %}">
            <img src="{% static 'images/view-list.svg' %}" width="30" height="30" alt="home logo"/>
            Listy prezentów
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'wish_list_app:view_reserved_gifts' %}">
            <img src="{% static 'images/gift.svg' %}" width="30" height="30" alt="home logo"/>
            Zarezerwowane prezenty
          </a>
        </li>
      </ul>
      {% if request.user.is_authenticated %}
        <div class="navbar-text p-3">
          <a class="nav-link" href="{% url 'home:user_info' %}">
            Witaj {{ request.user.first_name }}!
          </a>
        </div>
        <form method="post" action="{% url 'home:logout' %}">
            {% csrf_token %}
            <button class="btn btn-outline-dark px-4" type="submit">
             {% load static %}
              <img src="{% static 'images/box-arrow-left.svg' %}" width="30" height="30" alt="home logo"/>
              Wyloguj
            </button>
        </form>
      {% else %}
        <a type="button" class="btn btn-outline-dark" href="{% url 'home:login' %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M10 3.5a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 1 1 0v2A1.5 1.5 0 0 1 9.5 14h-8A1.5 1.5 0 0 1 0 12.5v-9A1.5 1.5 0 0 1 1.5 2h8A1.5 1.5 0 0 1 11 3.5v2a.5.5 0 0 1-1 0z"/>
            <path fill-rule="evenodd" d="M4.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H14.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708z"/>
          </svg>
          Zaloguj
        </a>
      {% endif %}
    </div>
  </div>
</nav>