home/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "home"
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("", views.home, name="home"),
    path("register/", views.register, name="register"),
    path("users/", views.get_users, name="users"),
    path("user_info", views.user_info, name="user_info"),
]

wish_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("", include("wish_list_app.urls", namespace="wish_list_app")),
    path("social-auth/", include("social_django.urls", namespace="social")),
]

wish_list_app/urls.py
from django.urls import path
from . import views

app_name = "wish_list_app"
urlpatterns = [
    path("wish_lists", views.view_all_wish_lists, name="all_wish_lists"),
    path("reserved_gifts/", views.view_reserved_gifts, name="view_reserved_gifts"),
    path("child_register", views.add_child_user, name="child_register"),
    path(
        "child_register_done/<username>",
        views.child_register_done,
        name="child_register_done",
    ),
    path("add_list", views.add_wish_list, name="add_wish_list"),
    path("add_list/<username>", views.add_wish_list, name="add_wish_list_user"),
    
    path("add_gift", views.add_gift, name="add_gift"),
    path("add_gift/<slug:list_name>", views.add_gift, name="add_gift_list"),
    path("reserved/<int:gift_id>", views.reserve_gift, name="reserve_gift"),
    path("find_meta", views.find_meta_info, name="find_meta"),
    path("delete_gift/<int:gift_id>", views.delete_gift, name="delete_gift"),
    path("cancel_gift_reservation/<int:gift_id>", views.cancel_gift_reservation, name="cancel_gift_reservation"),
    path(
        "<username>/<slug:list_name>/<slug:gift_slug>/edit/",
        views.edit_gift,
        name="edit_gift",
    ),
    path("<username>/<slug:list_name>/", views.view_wish_list_gifts, name="gift_lists"),
    path("<username>/", views.view_wish_list, name="user_lists"),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Hasło", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Powtórz hasło", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]

    def clean_password2(self):
        cd = self.cleaned_data
        if cd.get("password") != cd.get("password2"):
            raise forms.ValidationError("Hasła nie są takie same.")
        return cd.get("password2")

    def clean_email(self):
        data = self.cleaned_data.get("email")
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("Ten mail jest już zajęty.")
        return data

home/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from .forms import UserRegistrationForm


def home(request):
    return render(request, "home.html")


def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data.get("password"))
            # Save the User object
            new_user.save()
            return render(
                request, "registration/register_done.html", {"new_user": new_user}
            )
    else:
        user_form = UserRegistrationForm()

    return render(request, "registration/register.html", {"user_form": user_form})


def get_users(request):
    all_users = User.objects.filter(is_superuser=False)
    return render(request, "home/user_list.html", {"all_users": all_users})


def user_info(request):
    return render(request, "home/user_info.html", {"user": request.user})

home/templates/home/user_info.html
{% extends "base.html" %}

{% block title %}Informacje użytkownika{% endblock %}

{% block content %}
    <div class="px-4 pt-5 my-5 text-center">
        {% load static %}
        <h1 class="display-2 fw-bold">Witaj {{ user.username }}</h1>
            <div class="mx-auto p-2">
            <a type="button" class="btn btn btn-outline-primary btn-lg px-4" href="{% url 'wish_list_app:child_register' %}">
                <img src="{% static 'images/people.svg' %}" width="30" height="30" alt="home logo"/>
                Dodaj konto dziecka
            </a>
        </div>

    </div>

{% endblock %}

home/templates/home/user_list.html
{% extends "base.html" %}

{% block title %}Listy prezentów{% endblock %}

{% block content %}
    <div class="px-4 pt-5 my-5 text-center">
        <h1 class="display-2 fw-bold">Lista obdarowanych</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">Wybierz czyje listy prezentów chcesz obejrzeć</p>
        </div>
        {% if all_users %}
        <div class="list-group p-3">
            {% for user in all_users %}
            <a href="{% url 'wish_list_app:user_lists' user.username %}"
               class="list-group-item list-group-item-action display-6
               {% if forloop.counter0|divisibleby:2 %} list-group-item-primary{% endif %}"
            >
                {{ user.first_name }} {{ user.last_name }}
            </a>
            {% endfor %}
        </div>
        {% else %}
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">Brak użytkowników do wyświetlenia</p>
        </div>
        {% endif %}
    </div>

{% endblock %}