home/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "home"
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("", views.home, name="home"),
    path("register/", views.register, name="register"),
    path("users/", views.get_users, name="users"),
    path("user_info", views.user_info, name="user_info"),
]

wish_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("", include("wish_list_app.urls", namespace="wish_list_app")),
    path("social-auth/", include("social_django.urls", namespace="social")),
]

wish_list_app/urls.py
from django.urls import path
from . import views

app_name = "wish_list_app"
urlpatterns = [
    path("wish_lists", views.view_all_wish_lists, name="all_wish_lists"),
    path("reserved_gifts/", views.view_reserved_gifts, name="view_reserved_gifts"),
    path("child_register", views.add_child_user, name="child_register"),
    path(
        "child_register_done/<username>",
        views.child_register_done,
        name="child_register_done",
    ),
    path("add_list", views.add_wish_list, name="add_wish_list"),
    path("add_list/<username>", views.add_wish_list, name="add_wish_list_user"),
    
    path("add_gift", views.add_gift, name="add_gift"),
    path("add_gift/<slug:list_name>", views.add_gift, name="add_gift_list"),
    path("reserved/<int:gift_id>", views.reserve_gift, name="reserve_gift"),
    path("find_meta", views.find_meta_info, name="find_meta"),
    path("delete_gift/<int:gift_id>", views.delete_gift, name="delete_gift"),
    path("cancel_gift_reservation/<int:gift_id>", views.cancel_gift_reservation, name="cancel_gift_reservation"),
    path(
        "<username>/<slug:list_name>/<slug:gift_slug>/edit/",
        views.edit_gift,
        name="edit_gift",
    ),
    path("<username>/<slug:list_name>/", views.view_wish_list_gifts, name="gift_lists"),
    path("<username>/", views.view_wish_list, name="user_lists"),
]

wish_list_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class ChildUser(User):
    parent_user = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
        related_name="children",
        verbose_name="Rodzic",
    )

    email = None
    password = None

    class Meta:
        indexes = [models.Index(fields=["parent_user"])]
        verbose_name = "Użytkownik dziecko"
        verbose_name_plural = "Użytkownicy dziecko"

    def __str__(self):
        return f"Child: {self.username}, Parent: {self.parent_user.username}"


class WishList(models.Model):
    list_name = models.CharField(max_length=250, verbose_name="Nazwa listy")
    slug = models.SlugField(max_length=250)
    list_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="gift_lists_user",
        verbose_name="Obdarowany",
    )
    list_creator = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, related_name="gift_lists_creator"
    )

    class Meta:
        ordering = ["list_name"]
        indexes = [models.Index(fields=["list_user"])]
        verbose_name = "Lista prezentowa"
        verbose_name_plural = "Listy prezentowe"

    def __str__(self):
        return self.list_name

    def get_absolute_url(self):
        return reverse(
            "wish_list_app:gift_lists", args=[self.list_user.username, self.slug]
        )


class Gift(models.Model):
    gift_list = models.ForeignKey(
        WishList,
        on_delete=models.CASCADE,
        related_name="gift_item",
        verbose_name="Lista prezentów",
    )
    title = models.CharField(max_length=250, verbose_name="Co to za prezent")
    slug = models.SlugField(max_length=250)
    offer_url = models.URLField(null=True, blank=True, verbose_name="Link do oferty")
    image_url = models.URLField(null=True, blank=True, verbose_name="Link do zdjęcia")
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        default=None,
        related_name="gift_creator",
    )
    reserved = models.BooleanField(default=False)
    reserved_user = models.ForeignKey(
        User, models.SET_NULL, blank=True, null=True, verbose_name="Osoba rezerwująca"
    )
    reserved_time = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["created"]
        indexes = [models.Index(fields=["created"])]
        verbose_name = "Prezent"
        verbose_name_plural = "Prezenty"

    def __str__(self):
        return self.title

    def get_user_name(self):
        return self.gift_list.list_user.username

    def get_absolute_url(self):
        return reverse(
            "wish_list_app:gift_lists",
            args=[self.gift_list.list_user.username, self.gift_list.slug],
        )

    def get_reserved_url(self):
        return reverse(
            "wish_list_app:reserve_gift",
            args=[self.gift_list.list_user.username, self.gift_list.slug, self.slug],
        )

    def get_edit_url(self):
        return reverse(
            "wish_list_app:edit_gift",
            args=[self.gift_list.list_user.username, self.gift_list.slug, self.slug],
        )

wish_list_app/forms.py
from django import forms
from .models import ChildUser, WishList, Gift


class AddChildUser(forms.ModelForm):
    class Meta:
        model = ChildUser
        fields = ["username", "first_name", "last_name"]


class AddWishList(forms.ModelForm):
    class Meta:
        model = WishList
        fields = ["list_name", "list_user"]


class AddWishListUser(forms.ModelForm):
    class Meta:
        model = WishList
        fields = ["list_name"]


class AddGift(forms.ModelForm):

    class Meta:
        model = Gift
        fields = ["gift_list", "title", "offer_url", "image_url"]


class AddGiftToList(forms.ModelForm):

    class Meta:
        model = Gift
        fields = ["title", "offer_url", "image_url"]


class ReserveGift(forms.ModelForm):
    class Meta:
        model = Gift
        fields = ["id"]


class FindMetaForm(forms.Form):
    html = forms.CharField(widget=forms.Textarea)

wish_list_app/views.py
from datetime import datetime
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse


from .models import Gift, WishList
from .forms import (
    AddChildUser,
    AddWishList,
    AddWishListUser,
    AddGift,
    AddGiftToList,
    FindMetaForm,
)
from .get_meta.main import find_meta


@login_required
def add_child_user(request):
    # optional_parameter = ''
    form_object = AddChildUser

    if request.method == "POST":
        form = form_object(data=request.POST)
        if form.is_valid:
            new_child_user = form.save(commit=False)

            new_child_user.parent_user = request.user
            new_child_user.save()

            return redirect(
                "wish_list_app:child_register_done", username=new_child_user.username
            )
    else:
        form = form_object()
    return render(request, "child_register/child_register.html", {"form": form})


@login_required
def child_register_done(request, username):
    return render(
        request, "child_register/child_register_done.html", {"username": username}
    )


@login_required
def add_wish_list(request, username=None):
    # optional_parameter = ''
    list_user_object = None
    form_object = AddWishList
    if username is not None:
        list_user_object = get_object_or_404(User, username=username)
        form_object = AddWishListUser

    if request.method == "POST":
        form = form_object(data=request.POST)
        if form.is_valid:
            new_wish_list = form.save(commit=False)
            if username is not None:
                new_wish_list.list_user = list_user_object
            new_wish_list.list_creator = request.user
            new_wish_list.list_name = (
                f"{new_wish_list.list_user.first_name} {new_wish_list.list_user.last_name} "
                f"- {new_wish_list.list_name}"
            )
            new_wish_list.slug = slugify(new_wish_list.list_name)
            new_wish_list.save()
            return redirect(new_wish_list.get_absolute_url())
    else:
        form = form_object()
    return render(
        request,
        "wish_list_app/wish_lists/add_wish_list.html",
        {"user": list_user_object, "form": form},
    )


@login_required
def view_all_wish_lists(request):
    all_wish_lists = WishList.objects.all()
    return render(
        request,
        "wish_list_app/wish_lists/all_wish_lists.html",
        {"all_wish_lists": all_wish_lists},
    )


@login_required
def view_wish_list(request, username):
    list_user_object = get_object_or_404(User, username=username)
    user_wish_lists = list_user_object.gift_lists_user.all()
    list_number = user_wish_lists.count()
    return render(
        request,
        "wish_list_app/wish_lists/wish_lists.html",
        {"user": list_user_object, "user_wish_lists": user_wish_lists},
    )


@login_required
def view_wish_list_gifts(request, username, list_name):
    gift_list_object = get_object_or_404(
        WishList, list_user__username=username, slug=list_name
    )
    gift_list = gift_list_object.gift_item.filter(reserved=False)
    return render(
        request,
        "wish_list_app/gifts/gift_list.html",
        {"gift_list": gift_list, "list_name": gift_list_object},
    )


@login_required
def add_gift(request, list_name=None):
    form_object = AddGift
    list_object = None
    if list_name is not None:
        list_object = get_object_or_404(WishList, slug=list_name)
        form_object = AddGiftToList

    if request.method == "POST":
        form = form_object(request.POST)
        if form.is_valid:
            new_gift = form.save(commit=False)
            if list_name is not None:
                new_gift.gift_list = list_object
            else:
                list_object = new_gift.gift_list
            new_gift.slug = slugify(new_gift.title)
            new_gift.created_by = request.user
            new_gift.save()
            return redirect(list_object.get_absolute_url())
    else:
        form = form_object()

    return render(
        request,
        "wish_list_app/gifts/add_gift.html",
        {"list": list_object, "form": form},
    )


@login_required
def find_meta_info(request):
    meta_info = None
    if request.method == "POST":
        form = FindMetaForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            meta_info = find_meta(cd.get("html"))
    else:
        form = FindMetaForm()
    return render(
        request,
        "wish_list_app/add_item/find_meta.html",
        {"form": form, "meta_info": meta_info},
    )

@login_required
def view_reserved_gifts(request):
    reserved_gifts = Gift.objects.filter(reserved_user=request.user)
    return render(
        request,
        "wish_list_app/reservation/view_reserved.html",
        {"reserved_gifts": reserved_gifts},
    )


@login_required
def reserve_gift(request, gift_id):
    gift = get_object_or_404(Gift, id=gift_id)

    if request.method == "POST":
        gift.reserved = True
        gift.reserved_time = datetime.now()
        gift.reserved_user = request.user
        gift.save()
        return redirect(gift.get_absolute_url())

    return render(request, "wish_list_app/gifts/reserve_gift.html", {"gift": gift})


@login_required
def edit_gift(request, username, list_name, gift_slug):
    gift = get_object_or_404(
        Gift,
        gift_list__list_user__username=username,
        gift_list__slug=list_name,
        slug=gift_slug,
    )

    if request.method == "POST":
        form = AddGiftToList(instance=gift, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(gift.get_absolute_url())
    else:
        form = AddGiftToList(instance=gift)

    return render(
        request, "wish_list_app/gifts/edit_gift.html", {"form": form, "gift": gift}
    )


@login_required
def delete_gift(request, gift_id):
    gift = get_object_or_404(Gift, id=gift_id)

    if request.method == "POST":
        if (
            request.user == gift.created_by
            or request.user == gift.gift_list.list_creator
        ):
            list_url = gift.gift_list.get_absolute_url()
            gift.delete()
            return redirect(list_url)

    return render(request, "wish_list_app/gifts/delete_gift.html", {"gift": gift})

@login_required
def cancel_gift_reservation(request, gift_id):
    gift = get_object_or_404(Gift, id=gift_id)

    if request.method == "POST":
        if request.user == gift.reserved_user:
            gift.reserved = False
            gift.reserved_time = None
            gift.reserved_user = None
            gift.save()
            return redirect(reverse("wish_list_app:view_reserved_gifts"))

    return render(request, "wish_list_app/gifts/cancel_gift_reservation.html", {"gift": gift})

wish_list_app/templates/wish_list_app/wish_lists/add_wish_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Dodaj listę prezentów{% if user %} {{ user.username }}{% endif %}
{% endblock %}

{% block content %}
<div class="px-4 pt-5 my-5 text-center">
    <h1 class="display-5 fw-bold">
        Dodaj nową listę życzeń{% if user %} dla {{ user.first_name }} {{ user.last_name }}{% endif %}
    </h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">Wypełnij poniższy formularz i kliknij <strong>dodaj</strong> aby dodać nową listę.</p>
    </div>
    <form action="{{ gift.get_absolute_url }}" method="post">
        {{ form|crispy }}
        {% csrf_token %}
        <input class="btn btn-primary" type="submit" value="Dodaj">
    </form>
</div>
{% endblock %}

wish_list_app/templates/wish_list_app/wish_lists/all_wish_lists.html
{% extends "base.html" %}

{% block title %}Listy prezentów{% endblock %}

{% block content %}
        <div class="px-4 pt-5 my-5 text-center">
        <h1 class="display-2 fw-bold">Listy prezentów</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">Wybierz listę prezentów z poniższej listy aby przejrzeć życzenia.</p>
        </div>
        {% if all_wish_lists %}
            <div class="list-group p-3">
                {% for list in all_wish_lists %}
                <a href="{{ list.get_absolute_url }}"
                   class="list-group-item list-group-item-action display-6 list-group-item-primary">
                    {{ list.list_name }}
                </a>
                {% endfor %}
            </div>
        {% endif %}
        <hr class="mt-2 mb-3"/>
        <div class="mx-auto p-2">
            <a type="button" class="btn btn-primary btn-lg px-4" href="{% url 'wish_list_app:add_wish_list' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-lines-fill" viewBox="0 0 16 16">
                    <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5m.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1z"/>
                </svg>
                Dodaj nową listę prezentów
            </a>
        </div>
    </div>
{% endblock %}

wish_list_app/templates/wish_list_app/wish_lists/wish_lists.html
{% extends "base.html" %}

{% block title %}Listy prezentów {{ user.username }}{% endblock %}

{% block content %}
        <div class="px-4 pt-5 my-5 text-center">
        <h1 class="display-2 fw-bold">
            {{ user.first_name }} {{ user.last_name }} - Listy prezentów
        </h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">Wybierz listę prezentów z poniższej listy aby przejrzeć życzenia.</p>
        </div>
        {% if user_wish_lists %}
            <div class="list-group p-3">
                {% for list in user_wish_lists %}
                <a href="{{ list.get_absolute_url }}"
                   class="list-group-item list-group-item-action display-6 list-group-item-info">
                    {{ list.list_name }}
                </a>
                {% endfor %}
            </div>
        {% endif %}
        <hr class="mt-2 mb-3"/>
        <div class="mx-auto p-2">
            <a type="button" class="btn btn-info btn-lg px-4" href="{% url 'wish_list_app:add_wish_list_user' user.username %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-lines-fill" viewBox="0 0 16 16">
                    <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5m.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1z"/>
                </svg>
                Dodaj nową listę prezentów
            </a>
        </div>
    </div>
{% endblock %}